plex:
  url: "http://your-plex-server:32400"
  token: "PLEX_TOKEN_PLACEHOLDER"

tmdb:
  apiKey: "TMDB_API_KEY_PLACEHOLDER"
  language: "en-US"

fanart:
  enabled: true
  api_key: "FANART_TV_API_KEY_PLACEHOLDER"

overlays:
  enable: true
  path: "resources/overlays"

outputDirectory: "output/posters"
